Final final review
gdindzida/XLList pull request #4
Opened 2021-11-21 20:14 UTC by gdindzida

2021-11-21 20:24 UTC, ZerocksX commented on src/XLList.h
> +template<class DataType>
Tu je slobodno moglo `template <class T>`

2021-11-21 20:24 UTC, ZerocksX commented on src/XLList.h
> +
fali move assignment

2021-11-21 20:24 UTC, ZerocksX commented on src/XLList.h
> +    DataType getValue() const {
const T&

2021-11-21 20:24 UTC, ZerocksX commented on src/XLList.h
> +    XLList(const XLList<T> &other) = delete;
cim deklariras destruktor obrisu ti se move i copy constructor i assignment

2021-11-21 20:24 UTC, ZerocksX commented on src/XLList.h
> +    Node<T> *head;
probaj radije sa `std::unique_ptr<Node<T>>`
treba izbjegavati new i delete koliko god mozes

2021-11-21 20:24 UTC, ZerocksX commented on src/XLList.h
> +#include <iostream>
visak

2021-11-21 20:24 UTC, ZerocksX commented on src/XLList.h
> +    class Iterator : public std::iterator<std::random_access_iterator_tag, T, long int> {
ovo mozes staviti izvan klase da bude strukturiranije
pa kad ti treba lista::iterator samo stavis `using iterator = Iterator`;

2021-11-21 20:30 UTC, ZerocksX commented on src/XLList.h
> +            index = 0;
ovo je slobodno moglo u initializer list `index(0)`

2021-11-21 20:30 UTC, ZerocksX commented on src/XLList.h
> +        bool operator!=(const Iterator &comparingIterator) const;
je li ti stvarno treba sve ovo?

2021-11-21 20:30 UTC, ZerocksX commented on src/XLList.h
> +    T getElement(int index);
const?

2021-11-21 20:30 UTC, ZerocksX commented on src/XLList.h
> +    T popFront();
referenca?

2021-11-21 20:30 UTC, ZerocksX commented on src/XLList.h
> +    T popBack();
referenca?

2021-11-21 20:30 UTC, ZerocksX commented on src/XLList.h
> +typename XLList<T>::Iterator XLList<T>::Iterator::operator-(const long int &difference) const {
je li bas mora biti argument const long int&
uzmi ga kao long int pa mozes u tijelu `whlie(difference--)`

2021-11-21 20:30 UTC, ZerocksX commented on src/XLList.h
> +typename XLList<T>::Iterator XLList<T>::Iterator::operator-(const long int &difference) const {
provjeri je li stvarno tu ide long int ili mozda size_t, tj ptrdiff_t ili sto vec

2021-11-21 20:31 UTC, ZerocksX commented on src/XLList.h
> +    class Iterator : public std::iterator<std::random_access_iterator_tag, T, long int> {
nasljedivanje iz std::iterator je deprecate-ano

2021-12-01 21:55 UTC, hwnBEAST commented
General comments:
- put more effort into commit messages. In the future, when some line of code is controversial, or someone does not understand it, they will look into the commit messages. In the case the commit message is written sloppily, this can send the reader to a long search for the meaning (of the line of code). But in the case the commit message was carefully written that can same precious, frustating time,
- name MRs better,
- give introductory int he description of the MR,
- give a guide on how to run, and test the code.

2021-12-01 21:55 UTC, hwnBEAST commented on src/XLList.h
> +template<class DataType>
Disagree, but we do not have a coding standard to go against, so tankfully, we are both right.

2021-12-01 21:56 UTC, hwnBEAST commented on src/XLList.h
> +template<class DataType>
For this line, I would say replace class with `typename`, as this is what this keyword was created for, keep the long name.

2021-12-01 22:02 UTC, hwnBEAST commented on src/XLList.h
> +    class Iterator : public std::iterator<std::random_access_iterator_tag, T, long int> {
+1, usually, avoid defining class in a class (avoid class in class al together).  There are only small number of cases when class declaration in class is needed.

2021-12-01 22:51 UTC, hwnBEAST requested changes
First pass, I did not run the code, too lazy for now. I will do it next pass when code is in a better, more readable shape.

2021-12-01 22:51 UTC, hwnBEAST commented on README.md
> +LINK_size-1 = xor(*NODE_size-2, *HEAD).
This is the first time hearing about the XLList from me, nor can I find anything about it, but should this be the tail instead of the head?

2021-12-01 22:51 UTC, hwnBEAST commented on README.md
> + - xor(xor(A, B), C) = xor(A, xor(B, C))
Write the names of the operations.

2021-12-01 22:51 UTC, hwnBEAST commented on README.md
> +Head is special node. It doesn't contain data. It is helper node
Can the picture be edited, so data from HEAD is removed?

2021-12-01 22:51 UTC, hwnBEAST commented on src/CMakeLists.txt
> +set(HEADER_FILES
One thing of makefiles, cmake improves upon is makefiles's dependency on variables. CMake replaces the variables with the targets. And the building blocks of CMake is not the variables, rather the targets (libraries). Avoid using variables in CMake for this usecase.

2021-12-01 22:51 UTC, hwnBEAST commented on src/CMakeLists.txt
> +add_library(${BINARY}_lib STATIC ${INCLUDE_FILES})
Remove the variable.

separate this call into:
```
target_include_directries(${BINARY}_lib PRIVATE
...)
target_sources(${BINARY}_lib PRIVATE
...)
```

2021-12-01 22:51 UTC, hwnBEAST commented on src/CMakeLists.txt
> +add_executable(${BINARY}_run ${INCLUDE_FILES})
I am confused by this design, why do the `run` and `lib` targets exist? I have not seen this before.

2021-12-01 22:51 UTC, hwnBEAST commented on CMakeLists.txt
> +project(XLList)
```
project(XLList LANGUAGES CXX)
```

2021-12-01 22:51 UTC, hwnBEAST commented on CMakeLists.txt
> +include_directories(src)
Remove this, only set include directory per target.

2021-12-01 22:51 UTC, hwnBEAST commented on src/XLList.h
> +#include <iostream>
+1

2021-12-01 22:51 UTC, hwnBEAST commented on src/XLList.h
> +#ifndef XLLIST_XLLIST_H
NOTE RELATED TO THE LINE

I am not sure if this is relevant to your use-case, but in embedded we mix c and cpp code. That is why the extension for a cpp header of `.h` is problematic for me.  It is problematic because one can not differentiate between c and cpp code at a glance, and might include a cpp header with

```
extern "C"{
}
```

2021-12-01 22:51 UTC, hwnBEAST commented on src/main.cpp
> +{
Is this needed here?

2021-12-01 22:51 UTC, hwnBEAST commented on src/main.cpp
> +/*template <class T>
Remove comented code.

2021-12-01 22:51 UTC, hwnBEAST commented on test/CMakeLists.txt
> +set(SOURCE_FILES
Remove variables.

2021-12-01 22:51 UTC, hwnBEAST commented on test/XLList_test.cpp
> +TEST(xLListTest, testXORFunction) {
Name of the test shows that this is not an atomic test, as a unit test should be. Separate into multiple test of individual parts of the XOR.

2021-12-01 22:51 UTC, hwnBEAST commented on test/XLList_test.cpp
> +    ASSERT_EQ(beforeNodePtr, beforeNodeCalculated);
A good unit test usually only has one assert, and a sign of a bad one is multiple asserts. Now, I am too lazy to look into the code this time around, but it might prompt you to refactor it.

Why only one assert?

When a unit test fails, the author must (usually) without debugging (or long thinking session) figure out what is the problem.

2021-12-01 22:51 UTC, hwnBEAST commented on test/XLList_test.cpp
> +
I would separate these test into multiple one for the XLList, one for the XOR, one for the iterator, this file is getting long.

2021-12-01 22:51 UTC, hwnBEAST commented on test/main.cpp
> +int main(int argc, char **argv) {
There is a google test target that provides the main for you. Use it.

2021-12-01 22:51 UTC, hwnBEAST commented on src/XLList.h
> +        link = nullptr;
My opinion is that no definition must be present in a header file. This leads to a cleaner API. The way to do this with headers is declaring the classes, as normal ones, and putting a definition in a source file. How to compile it then?

At the end of the header file include the created source file. My preferred extension of these template definition source file is `.ctt` (in aconno we use `.cxx`).

2021-12-01 22:51 UTC, hwnBEAST commented on src/XLList.h
> +
+1.

2021-12-01 22:51 UTC, hwnBEAST commented on src/XLList.h
> +    DataType getValue() const {
- `DataType&& getValue() const && `

i dodaj i ovaj:

- `const DataType& getValue() const &`

2021-12-01 22:51 UTC, hwnBEAST commented on src/XLList.h
> +// Declaration
NOT RELATED TO THE LINE

- Mark all function `noexcept` as they are not throwing (even the ctors, dtors and operators)
- mark all functions `const` that can be invoked on a const class.

2021-12-01 22:51 UTC, hwnBEAST commented on src/XLList.h
> +struct Node {
Only one class per file is preferable, this leads to a better library design, as one always knows what is in a file. Change it this way.

2021-12-01 22:51 UTC, hwnBEAST commented on src/XLList.h
> +
I am not sure, but also a use of delegating constructor might be useful here. I will test next review pass.

2021-12-01 22:51 UTC, hwnBEAST commented on src/XLList.h
> +    class Iterator : public std::iterator<std::random_access_iterator_tag, T, long int> {
+1

2021-12-01 22:51 UTC, hwnBEAST commented on src/XLList.h
> +    class Iterator : public std::iterator<std::random_access_iterator_tag, T, long int> {
With cpp20 you can use, after the definition of this iterator, some iterator concept to check the validity of the iterator, e.g.,
```
static_assert(std::forward_iterator<XLList::Iterator>);
```
I do not know which one you are using, check here for the list of iterators:
- https://en.cppreference.com/w/cpp/iterator (title **C++20 iterator concepts**)

2021-12-01 22:51 UTC, hwnBEAST commented on src/XLList.h
> +            index = 0;
Prefer the curly braces when initializing values. [source](https://stackoverflow.com/questions/18222926/why-is-list-initialization-using-curly-braces-better-than-the-alternatives)

So this must be moved to initializer list + initializes as this: `index{0}`

2021-12-01 22:51 UTC, hwnBEAST commented on src/XLList.h
> +        bool operator!=(const Iterator &comparingIterator) const;
If yes, use the [spaceship operator](https://devblogs.microsoft.com/cppblog/simplify-your-code-with-rocket-science-c20s-spaceship-operator/), for operators it is applicable here.

And the question still stands, are there usecases for all of there operators? Prefer as little as possible implementation to satisfy your usecase!

2021-12-01 22:51 UTC, hwnBEAST commented on src/XLList.h
> +template<typename T>
Keep it consistent with tempale parameters, use a better name instead of `T`. T tells nothing about what type it is for.

2021-12-01 22:51 UTC, hwnBEAST commented on src/XLList.h
> +        // dubug info:
dubug -> debug. What is this comment even mean?

2021-12-01 22:51 UTC, hwnBEAST commented on src/XLList.h
> +    bool addElement(T newElement, int index);
What does bool mean? Add doxygen documentation to every function, and class!

2021-12-01 22:55 UTC, hwnBEAST commented on src/XLList.h
> +    Node<T> *head;
That is called, in cpp, RAII or SBRM, google those two terms, as they are pretty powerful ways of thinking. They are usually achieved by creating proxies over a "unsafe" piece of code, as raw pointers.

Now the only downside here is that the smart pointers require dynamic memory, from embedded side this would render them almost useless. But what is your usecase? Is this variable always going to be dynamic memory?

2024-10-13 14:51 UTC, closed without merging